server:
  port: 8081
spring:
  application:
    name: service-gateway
  profiles:
    active: after_route

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  profiles: after_route